### ISSUE TITLE
[zyn-fusion] MIDI program change doesn't select instruments from the active bank

### ISSUE THREAD

**Issue by michelesr** [zynaddsubfx/zyn-fusion-issues#354]
When using zyn-fusion interface, selecting a bank from the Browser view doesn't reflect the behavior of the old fltk interface: if I send a MIDI program change event, the instrument gets selected from the Arpeggio bank rather than the actual bank selected in the view. In the old interface, when a bank is selected, that bank is also used to select instruments when handling a MIDI program change event.

I've built `zynaddsubfx` with `-DGuiModule=fltk` and verified that the old interface works correctly, I tried building from zyn-fusion-build but I had some errors and couildn't get through building with zyn-fusion, but I verified the issue on version 3.0.6 installed on Arch Linux with pacman.   

I've also tried sending MIDI CC events 0 and 32, but they didn't change the active bank.

Edit: I've tried to build with `-DGuiModule=zest` and the produced binary runned with the zyn-fusion interface, and I could reproduce the issue (`zynaddsubfx --version` printed 3.0.7)

**Comment by fundamental** [comment]
resolved via https://github.com/zynaddsubfx/zynaddsubfx/pull/194

**Comment by michelesr** [comment]
While https://github.com/zynaddsubfx/zynaddsubfx/pull/194 solves midi cc events not being handled in the plugin, the UI still doesn't change the active bank when selecting a preset from the list, forcing you to either use a midi control event or the OSC interface. It would be nice it the behavior of the Zyn-Fusion UI could be consistent with the other UIs where selecting a preset from a bank shifts also the active bank and subsequent program changes will act within that bank
